version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - .env
# setup a newly created user with password and full database rights on the laravel database
    environment:
      - MYSQL_ROOT_PASSWORD=secure
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - laravel

  php:
    image: my-php-fpm:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    depends_on: 
      - laravel
      - composer
      - mysql
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel


  laravel:
    image: composer:latest
    container_name: laravel
    volumes:
      - ./:/app
    command: composer create-project --prefer-dist laravel/laravel src
    networks:
      - laravel

  composer:
    image: composer:latest
    depends_on: 
      - laravel
    container_name: composer
    volumes:
      - ./:/app
    command: bash -c "composer install && chown -R www-data:www-data /var/www/html && date"
    networks:
      - laravel
